/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package wordCounter

import wordCounter.exceptions.NoFileException

import static wordCounter.services.FileReader.readFileToString
import static wordCounter.services.WordCounter.countWords

class App {
    static String getWordCount(String relativeFilePath) {
        try {
            String result = ""
            String text = readFileToString(relativeFilePath)
            Map<String, Integer> wordCount = countWords(text)
            for (count in wordCount) {
                result = result.concat(count.key + ": " + count.value + "\n")
            }
            return result
        } catch (NoFileException exception) {
            return exception.message + ", please ensure you are giving relative filepath"
        }
    }

    static void main(String[] args) {
        if (!args || args.length == 0) {
            print "No file path supplied, please re-run and give relative filepath as CLI arg"
        } else if (args.length > 1) {
            print "Too many args supplied, please re-run with only one filepath supplied"
        } else {
            print getWordCount(args[0])
        }
    }
}
