/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package wordCounter

import groovy.test.GroovyTestCase

class AppTest extends GroovyTestCase {
    void testApp() {
        assertEquals("Test", "Test")
    }
}
