/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package word.counter

class App {

    static void main(String[] args) {
        String pathToFile
        if (!args) {
            pathToFile = System.console().readLine 'Please provide path to file: '
        } else if (args.length > 1) {
            println "Please only supply one path"
        } else {
            pathToFile = args[0]
        }
        println pathToFile
    }
}
