name: Word Counter Pipeline
run-name: Running test and build of Word Counter 🚀
on: [push]
jobs:
  test-project:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run all tests
        run: ./gradlew clean test
      - run: echo "This job's status is ${{ job.status }}."
  build-project:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build project
        run: ./gradlew clean build
      - run: echo "This job's status is ${{ job.status }}."
